#pragma once
#include <winsock2.h>
#include <WS2tcpip.h>
#include <Windows.h>
#include <wincrypt.h>
#include <sqlite3.h>
#include <string>
#include <fstream>
#include <iostream>
#include <wininet.h>  
#include <gdiplus.h>  
#include <chrono>
#include <sstream>
#include <iomanip>
#include <shellapi.h>
#include <shlobj.h>
#include <objidl.h>
#include <atlbase.h>
#include <iphlpapi.h>
#include <shlwapi.h>
#include <comdef.h>
#include <vector>
#include <cstdlib>
#include <curl/curl.h>
#include <nlohmann/json.hpp>
#include <thread>
